language: java
jdk:
  - openjdk11

install: TRUE
script: ./gradlew build

# Some Gradle nuance
before_cache:
  rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    $HOME/.gradle/caches/
    $HOME/.gradle/wrapper/

# Generate and deploy Javadoc
before_deploy:
  ./gradlew fulldoc
deploy:
  # Deploy Javadoc
  - provider: pages
    github_token: $GH_PAGES_TOKEN
    local_dir: build/docs
    skip_cleanup: true
    on:
      branch: master
  # Publish
  - provider: script
    script: ./gradlew bintray
    skip_cleanup: true
    on:
      branch: master
